# Generated by Django 4.0.1 on 2022-05-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaccount',
            name='id_college',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
