# Generated by Django 4.0.1 on 2022-05-18 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answerd_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 9, 46, 52, 840575)),
        ),
        migrations.AlterField(
            model_name='reportresult',
            name='on_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 9, 46, 52, 841542)),
        ),
    ]
