# Generated by Django 4.0.1 on 2022-05-18 04:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('on_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('about', models.CharField(choices=[('become_company', 'About.. become company'), ('admin', 'About.. as admin'), ('instructor', 'About.. as Instructor'), ('student', 'About.. as student'), ('parent', 'About.. as parent'), ('course', 'About.. course'), ('quiz', 'About.. quiz')], max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
