# Generated by Django 4.0.1 on 2022-05-18 04:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='InstructorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_schedule_name', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=50)),
                ('instructor_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=20)),
                ('Schedule_name', models.CharField(max_length=50)),
                ('slide', models.FileField(upload_to='materials/slide/%Y/%m/%d/')),
                ('company_name', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=20)),
                ('Schedule_name', models.CharField(max_length=50)),
                ('lecture_video', models.FileField(upload_to='materials/videos/%Y/%m/%d/')),
                ('company_name', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_have_post', models.CharField(max_length=50)),
                ('post_title', models.CharField(max_length=30)),
                ('Schedule_name', models.CharField(max_length=50)),
                ('post_file', models.FileField(upload_to='posts/%Y/%m/%d/')),
                ('post_description', models.TextField()),
                ('company_name', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_name', models.CharField(max_length=30, unique=True)),
                ('company_name', models.CharField(max_length=50)),
                ('course_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_schedule_name', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=30)),
                ('can_post', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TaskInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('task_file', models.FileField(upload_to='tasks/%Y/%m/%d/')),
                ('company_name', models.CharField(max_length=50)),
                ('Schedule_name', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TaskStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_username', models.CharField(max_length=40)),
                ('std_company', models.CharField(max_length=40)),
                ('std_task_name', models.TextField()),
                ('std_schedule', models.TextField()),
                ('std_task_file', models.FileField(upload_to='tasks/ans/%Y/%m/%d/')),
                ('std_task_d', models.IntegerField()),
                ('is_download', models.BooleanField(default=False)),
            ],
        ),
    ]
